# 使用官方 Python 镜像作为基础镜像
FROM python:3.11-slim

# 设置工作目录
WORKDIR /app

# 复制项目的需求文件到工作目录
COPY requirements.txt .

# 安装项目依赖
RUN pip install --no-cache-dir -r requirements.txt

# 复制项目的全部代码到工作目录
COPY . .

# 设置环境变量
ENV OPENAI_API_KEY=<your_openai_api_key>
# proxy example for using clash: ENV HTTP_PROXY=http://host.docker.internal:7890 
ENV HTTP_PROXY=<your_http_proxy> 
ENV HTTPS_PROXY=<your_https_proxy>

# 暴露应用所需的端口
EXPOSE 8000

# 启动应用
CMD ["python", "app.py"]
